# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Dto/'
            - '../src/Enums/'
            - '../src/Exceptions/'

    App\Repositories\TariffRepository:
        arguments:
            $tariffsDirectory: '%kernel.project_dir%/config/shipping'

    App\Repositories\ZoneRepository:
        arguments:
            $zoneFilePath: '%kernel.project_dir%/config/shipping/zones.yaml'

    App\Repositories\SettingsRepository:
        arguments:
            $settingsFilePath: '%kernel.project_dir%/config/shipping/settings.json'