nelmio_api_doc:
    documentation:
        info:
            title: Shipping API
            description: API za izračun poštarine
            version: 1.0.0
    areas: # Ovdje definiramo koje kontrolere skeniramo
        path_patterns:
            - ^/api(?!/doc$) # Skeniraj sve rute koje počinju s /api